import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "../utils/api";

const Success: NextPage = () => {
  const router = useRouter();
  const email = useRouter().query.email as string;

  const isPaid = api.payment.isPaidEmail.useQuery(
    { email },
    {
      enabled: router.isReady,
    }
  );

  return (
    <>
      <Head>
        <title>Learn</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        {isPaid.data?.isValid ? (
          <iframe
            width="560"
            height="315"
            src="https://www.youtube.com/embed/qv6-IBfYFDg"
            title="YouTube video player"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowFullScreen
          ></iframe>
        ) : (
          "validating email..."
        )}
      </main>
    </>
  );
};

export default Success;
