import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";
import { env } from "../env/client.mjs";

const Success: NextPage = () => {
  return (
    <>
      <Head>
        <title>Success!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        Success!
        <iframe
          width="560"
          height="315"
          src="https://www.youtube.com/embed/qv6-IBfYFDg"
          title="YouTube video player"
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowfullscreen
        ></iframe>
      </main>
    </>
  );
};

export default Home;
